name: flutter_scafflod
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fluent_ui: ^4.7.3
  flutter_acrylic: ^1.0.0+2
  system_theme: ^2.1.0
  flukit: ^3.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^6.2.0
  window_manager: ^0.3.5
  fluentui_system_icons: ^1.1.211


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true